#!/usr/bin/env python3
"""Build a self-contained Stash Android profile from local repository resources."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def nonempty_lines(path: Path) -> list[str]:
    return [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def read_provider(path: Path) -> tuple[list[str], list[str]]:
    content = path.read_text(encoding="utf-8")
    chunks = re.split(r"(?=^  - name: )", content, flags=re.MULTILINE)
    nodes = [chunk for chunk in chunks[1:] if chunk.strip()]
    names = []
    for node in nodes:
        match = re.match(r'^  - name: ([^\n]+)', node)
        if not match:
            raise ValueError("provider node has no name")
        names.append(json.loads(match.group(1)))
    if not nodes:
        raise ValueError("provider is empty")
    return nodes, names


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--provider", type=Path, required=True)
    parser.add_argument("--domains", type=Path, required=True)
    parser.add_argument("--ipv4", type=Path, required=True)
    parser.add_argument("--ipv6", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    nodes, names = read_provider(args.provider)
    domain_rules = [f"  - DOMAIN-SUFFIX,{domain.removeprefix('+.')},DIRECT" for domain in nonempty_lines(args.domains)]
    ipv4_rules = [f"  - IP-CIDR,{cidr},DIRECT,no-resolve" for cidr in nonempty_lines(args.ipv4)]
    ipv6_rules = [f"  - IP-CIDR6,{cidr},DIRECT,no-resolve" for cidr in nonempty_lines(args.ipv6)]

    lines = [
        "#SUBSCRIBED https://raw.githubusercontent.com/anthonyandreew/sub/main/clash_config_android.yaml",
        "# Generated by scripts/build_android_config.py. Do not edit manually.",
        "# Android Early Access: static nodes and rules avoid remote provider loading.",
        "",
        "mode: rule",
        "log-level: warning",
        "",
        "dns:",
        "  enable: true",
        "  default-nameserver:",
        "    - https://8.8.8.8/dns-query",
        "  nameserver:",
        "    - https://dns.google/dns-query",
        "",
        "proxies:",
    ]
    content = "\n".join(lines) + "\n" + "".join(nodes)
    content += "\nproxy-groups:\n  - name: PROXY\n    type: select\n    proxies:\n"
    content += "".join(f"      - {json.dumps(name, ensure_ascii=False)}\n" for name in names)
    content += "\nrules:\n"
    content += "\n".join([
        "  - DOMAIN-SUFFIX,local,DIRECT",
        "  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
        "  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve",
        "  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
        "  - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve",
        "  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
        "  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
        "  - IP-CIDR6,::1/128,DIRECT,no-resolve",
        "  - IP-CIDR6,fc00::/7,DIRECT,no-resolve",
        "  - IP-CIDR6,fe80::/10,DIRECT,no-resolve",
        *domain_rules,
        *ipv4_rules,
        *ipv6_rules,
        "  - MATCH,PROXY",
    ])
    args.output.write_text(content + "\n", encoding="utf-8")
    print(f"Generated Android config with {len(names)} nodes and {len(domain_rules) + len(ipv4_rules) + len(ipv6_rules)} direct rules")


if __name__ == "__main__":
    main()
